version: '3.7'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    profiles:
      - "request"
    depends_on:
      - redis

  celery:
    build: .
    command: poetry run celery -A src.celery.celery worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis

  celery-beat:
    build: .
    command: poetry run celery -A src.celery.celery beat --loglevel=info
    env_file:
      - .env
    profiles:
      - "schedule"
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
