name: continous-integration
on: 
  push:
  workflow_call:

jobs:
  code-format-check:
    name: check code formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--check"
    
  run-tests:
    strategy:
      fail-fast: false
    name: run pytest
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
    
      - name: setup python
        uses: actions/setup-python@v4
        with:
            python-version: 3.9.13
      
      - name: install dependencies
        run: |
          python -m pip install poetry
          poetry install
      
      - name: run tests
        run: pytest --disable-warnings
