name: sonarcloud
on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
    
jobs:
  sonarcloud:
    if: '! github.event.pull_request.draft'
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo with submodules
        uses: actions/checkout@v3

      - name: sonarcloud scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: sonarcloud quality gate check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}